//  we will create user permissions
const PERMISSIONS = {
  "all-permissions": "all-permissions",
  "get-users": "get-users",
  "get-user": "get-user",
  "create-user": "create-user",
  "update-user": "update-user",
  "create-country": "create-country",
  // "get-countries": "get-countries",
  "get-country": "get-country",
  "update-country": "update-country",
  "create-city": "create-city",
  // "get-cities": "get-cities",
  "get-city": "get-city",
  "update-city": "update-city",
  "create-area": "create-area",
  // "get-areas": "get-areas",
  "get-area": "get-area",
  "update-area": "update-area",
  // "get-categories": "get-categories",
  "get-category": "get-category",
  "create-category": "create-category",
  "update-category": "update-category",

  "get-products": "get-products",
  "get-product": "get-product",
  "create-product": "create-product",
  "update-product": "update-product",
  "delete-product-image": "delete-product-image",
};
module.exports = PERMISSIONS;
